version: '2'
services:
    mymicroserviceapp-app:
        image: mymicroserviceapp
        external_links:
            - mymicroserviceapp-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mymicroserviceapp
    mymicroserviceapp-mongodb:
        extends:
            file: mongodb.yml
            service: mymicroserviceapp-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
