version: '2'
services:
    mymicroserviceapp-mongodb:
        container_name: mymicroserviceapp-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb mymicroserviceapp-mongodb-config
    mymicroserviceapp-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    mymicroserviceapp-mongodb-config:
        image: mongo:3.2.3
        container_name: mymicroserviceapp-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
