version: '2'
services:
    mymicroserviceapp-mongodb:
        container_name: mymicroserviceapp-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/mymicroserviceapp/mongodb/:/data/db/
